[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datakit"
dynamic = ["version"]
description = "Datakit utilities"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = ["click", "numpy", "pandas", "rich", "mesokit-schema"]

[project.optional-dependencies]
explore = ["rich"]

[project.scripts]
datakit = "datakit.cli.datakit:datakit"

[tool.setuptools]
package-dir = { datakit = "datakit" }
packages = [
    "datakit",
    "datakit.cli",
    "datakit.sources",
    "datakit.sources.analysis",
    "datakit.sources.behavior",
    "datakit.sources.camera",
    "datakit.sources.session",
    "datakit._utils",
]

[tool.setuptools.dynamic]
version = { file = "VERSION" }
